# Generated by Django 2.0.9 on 2020-07-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='school_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='School Name'),
        ),
    ]
