# Generated by Django 2.0.9 on 2020-07-23 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200723_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='prog2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='prog3',
        ),
    ]
