# Generated by Django 2.0.9 on 2020-07-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20200727_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='quiz3',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Participant'),
        ),
        migrations.AddField(
            model_name='profile',
            name='quiz4',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Participant'),
        ),
    ]
