# Generated by Django 2.0.9 on 2020-07-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20200730_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='s1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='s2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Contact No.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='s3',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Email Id'),
        ),
        migrations.AddField(
            model_name='profile',
            name='t1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='t2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Contact No.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='t3',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Email Id'),
        ),
    ]
