# Generated by Django 2.0.9 on 2020-07-20 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authtools', '0003_auto_20160128_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('student1', models.CharField(blank=True, max_length=30, null=True, verbose_name='Student 1')),
                ('student2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Student 1')),
            ],
        ),
    ]
