# Generated by Django 2.0.9 on 2020-07-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reg',
            name='student1',
        ),
        migrations.RemoveField(
            model_name='reg',
            name='student2',
        ),
        migrations.AddField(
            model_name='reg',
            name='cross1',
            field=models.CharField(max_length=30, null=True, verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='reg',
            name='cross2',
            field=models.CharField(max_length=30, null=True, verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='reg',
            name='hack1',
            field=models.CharField(max_length=30, null=True, verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='reg',
            name='hack2',
            field=models.CharField(max_length=30, null=True, verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='reg',
            name='hack3',
            field=models.CharField(max_length=30, null=True, verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='reg',
            name='hack4',
            field=models.CharField(max_length=30, null=True, verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='reg',
            name='hard1',
            field=models.CharField(max_length=30, null=True, verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='reg',
            name='hard2',
            field=models.CharField(max_length=30, null=True, verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='reg',
            name='prog1',
            field=models.CharField(max_length=30, null=True, verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='reg',
            name='prog2',
            field=models.CharField(max_length=30, null=True, verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='reg',
            name='quiz1',
            field=models.CharField(max_length=30, null=True, verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='reg',
            name='quiz2',
            field=models.CharField(max_length=30, null=True, verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='reg',
            name='surp1',
            field=models.CharField(max_length=30, null=True, verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='reg',
            name='surp2',
            field=models.CharField(max_length=30, null=True, verbose_name='Student'),
        ),
    ]
