# Generated by Django 2.0.9 on 2020-07-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20200723_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hack4',
        ),
        migrations.AddField(
            model_name='profile',
            name='av1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Participant'),
        ),
        migrations.AddField(
            model_name='profile',
            name='av2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Participant'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cross3',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Participant'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cross4',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Participant'),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Participant'),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Participant'),
        ),
        migrations.AddField(
            model_name='profile',
            name='surp3',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Participant'),
        ),
        migrations.AddField(
            model_name='profile',
            name='surp4',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Participant'),
        ),
    ]
