# Generated by Django 2.0.9 on 2020-07-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20200727_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='quiz3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='quiz4',
        ),
        migrations.AddField(
            model_name='profile',
            name='photo3',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Team 2'),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo4',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Team 2'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cross1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Team 1'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cross2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Team 1'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cross3',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Team 2'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cross4',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Team 2'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hard1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Team 1'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hard2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Team 2'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Team 1'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Team 1'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='quiz1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Team 1'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='quiz2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Team 2'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='surp1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Team 1'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='surp2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Team 1'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='surp3',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Team 2'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='surp4',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Team 2'),
        ),
    ]
