# Generated by Django 2.0.9 on 2020-07-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20200730_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='av1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Team 1'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='av2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Team 2'),
        ),
    ]
